<dec f='tcc/tcc.h' l='419' type='int'/>
<use f='tcc/i386-asm.c' l='511' u='r' c='gen_disp32'/>
<use f='tcc/i386-asm.c' l='512' u='w' c='gen_disp32'/>
<use f='tcc/i386-asm.c' l='1533' u='r' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1534' u='r' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1536' u='r' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1539' u='r' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1540' u='r' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1641' u='w' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1665' u='w' c='asm_gen_code'/>
<offset>0</offset>
<use f='tcc/tccasm.c' l='380' macro='1' u='r' c='asm_new_label1'/>
<use f='tcc/tccasm.c' l='381' u='r' c='asm_new_label1'/>
<use f='tcc/tccasm.c' l='383' u='r' c='asm_new_label1'/>
<use f='tcc/tccasm.c' l='397' u='w' c='asm_new_label1'/>
<use f='tcc/tccasm.c' l='681' u='w' c='asm_parse_directive'/>
<use f='tcc/tccasm.c' l='811' u='w' c='asm_parse_directive'/>
<use f='tcc/tccasm.c' l='811' u='r' c='asm_parse_directive'/>
<use f='tcc/tccasm.c' l='815' u='r' c='asm_parse_directive'/>
<use f='tcc/tccasm.c' l='1118' u='r' c='parse_asm_operands'/>
<use f='tcc/tccgen.c' l='216' u='r' c='tcc_debug_funcstart'/>
<use f='tcc/tccgen.c' l='245' u='w' c='tccgen_compile'/>
<use f='tcc/tccgen.c' l='246' u='w' c='tccgen_compile'/>
<use f='tcc/tccgen.c' l='255' u='w' c='tccgen_compile'/>
<use f='tcc/tccgen.c' l='256' u='w' c='tccgen_compile'/>
<use f='tcc/tccgen.c' l='258' u='w' c='tccgen_compile'/>
<use f='tcc/tccgen.c' l='305' u='r' c='update_storage'/>
<use f='tcc/tccgen.c' l='379' u='r' c='put_extern_sym2'/>
<use f='tcc/tccgen.c' l='508' u='w' c='sym_push2'/>
<use f='tcc/tccgen.c' l='558' u='r' c='sym_push'/>
<use f='tcc/tccgen.c' l='722' u='w' c='vpush64'/>
<use f='tcc/tccgen.c' l='745' u='w' c='vseti'/>
<use f='tcc/tccgen.c' l='815' u='r' c='get_sym_ref'/>
<use f='tcc/tccgen.c' l='836' u='r' c='external_global_sym'/>
<use f='tcc/tccgen.c' l='839' macro='1' u='r' c='external_global_sym'/>
<use f='tcc/tccgen.c' l='840' u='w' c='external_global_sym'/>
<use f='tcc/tccgen.c' l='840' u='r' c='external_global_sym'/>
<use f='tcc/tccgen.c' l='840' u='r' c='external_global_sym'/>
<use f='tcc/tccgen.c' l='850' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='851' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='853' u='w' c='patch_type'/>
<use f='tcc/tccgen.c' l='856' macro='1' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='858' u='w' c='patch_type'/>
<use f='tcc/tccgen.c' l='858' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='858' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='866' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='867' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='869' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='869' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='873' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='875' u='w' c='patch_type'/>
<use f='tcc/tccgen.c' l='875' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='876' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='877' u='w' c='patch_type'/>
<use f='tcc/tccgen.c' l='877' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='882' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='889' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='889' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='933' u='w' c='external_sym'/>
<use f='tcc/tccgen.c' l='940' u='w' c='external_sym'/>
<use f='tcc/tccgen.c' l='985' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='993' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='993' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1001' u='w' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1001' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1028' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1109' u='w' c='move_reg'/>
<use f='tcc/tccgen.c' l='1143' u='w' c='gbound'/>
<use f='tcc/tccgen.c' l='1162' u='w' c='incr_bf_adr'/>
<use f='tcc/tccgen.c' l='1162' u='r' c='incr_bf_adr'/>
<use f='tcc/tccgen.c' l='1173' u='r' c='load_packed_bf'/>
<use f='tcc/tccgen.c' l='1194' u='r' c='load_packed_bf'/>
<use f='tcc/tccgen.c' l='1195' u='r' c='load_packed_bf'/>
<use f='tcc/tccgen.c' l='1244' u='w' c='adjust_bf'/>
<use f='tcc/tccgen.c' l='1244' u='r' c='adjust_bf'/>
<use f='tcc/tccgen.c' l='1245' u='r' c='adjust_bf'/>
<use f='tcc/tccgen.c' l='1258' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1261' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1262' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1264' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1267' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1267' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1268' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1269' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1273' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1274' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1276' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1281' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1293' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1330' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1331' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1339' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1339' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1340' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1347' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1372' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1377' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1382' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1397' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1398' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1402' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1411' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1414' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1555' u='r' c='gv_dup'/>
<use f='tcc/tccgen.c' l='1580' u='w' c='gv_dup'/>
<use f='tcc/tccgen.c' l='1588' u='w' c='gv_dup'/>
<use f='tcc/tccgen.c' l='1868' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1869' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1878' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1881' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1934' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='2030' u='r' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2033' u='r' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2063' u='r' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2065' u='r' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2093' u='r' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2094' u='r' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2095' u='r' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2116' u='r' c='check_comparison_pointer_types'/>
<use f='tcc/tccgen.c' l='2117' u='r' c='check_comparison_pointer_types'/>
<use f='tcc/tccgen.c' l='2137' u='r' c='check_comparison_pointer_types'/>
<use f='tcc/tccgen.c' l='2138' u='r' c='check_comparison_pointer_types'/>
<use f='tcc/tccgen.c' l='2142' u='w' c='check_comparison_pointer_types'/>
<use f='tcc/tccgen.c' l='2143' u='w' c='check_comparison_pointer_types'/>
<use f='tcc/tccgen.c' l='2160' u='r' c='gen_op'/>
<use f='tcc/tccgen.c' l='2161' u='r' c='gen_op'/>
<use f='tcc/tccgen.c' l='2198' u='r' c='gen_op'/>
<use f='tcc/tccgen.c' l='2205' u='w' c='gen_op'/>
<use f='tcc/tccgen.c' l='2205' u='r' c='gen_op'/>
<use f='tcc/tccgen.c' l='2223' u='w' c='gen_op'/>
<use f='tcc/tccgen.c' l='2224' u='r' c='gen_op'/>
<use f='tcc/tccgen.c' l='2332' u='w' c='gen_op'/>
<use f='tcc/tccgen.c' l='2339' u='w' c='gen_op'/>
<use f='tcc/tccgen.c' l='2347' u='w' c='gen_op'/>
<use f='tcc/tccgen.c' l='2349' u='w' c='gen_op'/>
<use f='tcc/tccgen.c' l='2354' u='r' c='gen_op'/>
<use f='tcc/tccgen.c' l='2364' u='r' c='gen_cvt_itof1'/>
<use f='tcc/tccgen.c' l='2396' u='r' c='gen_cvt_ftoi1'/>
<use f='tcc/tccgen.c' l='2435' u='r' c='force_charshort_cast'/>
<use f='tcc/tccgen.c' l='2444' u='w' c='force_charshort_cast'/>
<use f='tcc/tccgen.c' l='2454' u='w' c='gen_cast_s'/>
<use f='tcc/tccgen.c' l='2468' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2472' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2476' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2477' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2571' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2573' u='w' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2631' u='w' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2653' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2664' u='r' c='type_size'/>
<use f='tcc/tccgen.c' l='2671' u='r' c='type_size'/>
<use f='tcc/tccgen.c' l='2685' u='r' c='type_size'/>
<use f='tcc/tccgen.c' l='2727' u='r' c='vla_runtime_type_size'/>
<use f='tcc/tccgen.c' l='2758' u='w' c='mk_pointer'/>
<use f='tcc/tccgen.c' l='2758' u='r' c='mk_pointer'/>
<use f='tcc/tccgen.c' l='2801' u='r' c='compare_types'/>
<use f='tcc/tccgen.c' l='2802' u='r' c='compare_types'/>
<use f='tcc/tccgen.c' l='2859' u='r' c='type_to_str'/>
<use f='tcc/tccgen.c' l='2981' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='2982' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='2997' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3013' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3021' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3022' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3032' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3032' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3033' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3033' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3039' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3039' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3040' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3040' u='r' c='gen_assign_cast'/>
<use f='tcc/tccgen.c' l='3073' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3074' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3078' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3081' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3099' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3116' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3132' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3136' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3136' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3147' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3161' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3200' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3212' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3217' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3221' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3227' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3465' u='r' c='find_field'/>
<use f='tcc/tccgen.c' l='3481' u='r' c='struct_add_offset'/>
<use f='tcc/tccgen.c' l='3507' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3508' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3537' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3580' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3580' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3595' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3619' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3619' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3638' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3703' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3707' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3710' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3725' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3727' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3729' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3731' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3741' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3741' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3744' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3782' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3784' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3792' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3798' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3798' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3813' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3844' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3847' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3848' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3850' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3851' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3851' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3851' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3858' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3859' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3863' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3863' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3885' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3896' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3902' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3903' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3921' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3939' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3939' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3944' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3952' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3991' u='r' c='parse_btype_qualify'/>
<use f='tcc/tccgen.c' l='3995' u='w' c='parse_btype_qualify'/>
<use f='tcc/tccgen.c' l='4085' u='r' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4099' u='w' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4101' u='r' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4107' u='w' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4109' u='r' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4175' u='w' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4183' u='r' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4187' u='w' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4187' u='r' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4191' u='r' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4214' u='w' c='parse_btype'/>
<use f='tcc/tccgen.c' l='4224' u='w' c='convert_parameter_type'/>
<use f='tcc/tccgen.c' l='4226' u='w' c='convert_parameter_type'/>
<use f='tcc/tccgen.c' l='4227' u='r' c='convert_parameter_type'/>
<use f='tcc/tccgen.c' l='4282' u='r' c='post_type'/>
<use f='tcc/tccgen.c' l='4285' u='r' c='post_type'/>
<use f='tcc/tccgen.c' l='4292' u='w' c='post_type'/>
<use f='tcc/tccgen.c' l='4316' u='w' c='post_type'/>
<use f='tcc/tccgen.c' l='4332' u='w' c='post_type'/>
<use f='tcc/tccgen.c' l='4358' u='r' c='post_type'/>
<use f='tcc/tccgen.c' l='4366' u='r' c='post_type'/>
<use f='tcc/tccgen.c' l='4368' u='r' c='post_type'/>
<use f='tcc/tccgen.c' l='4388' u='w' c='post_type'/>
<use f='tcc/tccgen.c' l='4407' u='r' c='type_decl'/>
<use f='tcc/tccgen.c' l='4408' u='w' c='type_decl'/>
<use f='tcc/tccgen.c' l='4437' u='w' c='type_decl'/>
<use f='tcc/tccgen.c' l='4466' u='w' c='type_decl'/>
<use f='tcc/tccgen.c' l='4490' u='r' c='indir'/>
<use f='tcc/tccgen.c' l='4491' u='r' c='indir'/>
<use f='tcc/tccgen.c' l='4499' u='r' c='indir'/>
<use f='tcc/tccgen.c' l='4499' u='r' c='indir'/>
<use f='tcc/tccgen.c' l='4500' u='r' c='indir'/>
<use f='tcc/tccgen.c' l='4501' u='r' c='indir'/>
<use f='tcc/tccgen.c' l='4520' u='r' c='gfunc_param_typed'/>
<use f='tcc/tccgen.c' l='4522' u='r' c='gfunc_param_typed'/>
<use f='tcc/tccgen.c' l='4523' u='w' c='gfunc_param_typed'/>
<use f='tcc/tccgen.c' l='4523' u='r' c='gfunc_param_typed'/>
<use f='tcc/tccgen.c' l='4531' u='w' c='gfunc_param_typed'/>
<use f='tcc/tccgen.c' l='4620' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4659' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4661' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4686' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4688' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4706' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4707' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4750' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4751' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4778' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4783' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4800' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4810' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4820' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4821' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4875' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4952' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4982' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4983' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='4985' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5002' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5073' macro='1' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5104' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5120' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5124' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5140' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5142' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5143' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5163' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5165' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5167' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5183' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5215' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5216' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5218' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5224' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5258' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5494' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5497' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5540' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5542' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5549' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5552' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5554' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5558' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5560' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5562' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5566' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5586' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5589' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5593' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5597' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5606' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5611' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5614' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5618' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5639' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5645' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5746' u='r' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='5778' u='r' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='5779' u='r' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='5800' u='r' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='5801' u='r' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='5820' u='r' c='gcase'/>
<use f='tcc/tccgen.c' l='5888' u='w' c='block'/>
<use f='tcc/tccgen.c' l='6003' u='r' c='block'/>
<use f='tcc/tccgen.c' l='6122' u='r' c='block'/>
<use f='tcc/tccgen.c' l='6123' u='w' c='block'/>
<use f='tcc/tccgen.c' l='6170' u='r' c='block'/>
<use f='tcc/tccgen.c' l='6343' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6367' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6386' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6394' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6448' u='w' c='init_putv'/>
<use f='tcc/tccgen.c' l='6455' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6461' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6488' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6528' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6531' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6532' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6659' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6665' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6687' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6689' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6745' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6753' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6774' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6832' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='6836' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='6841' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='6905' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='6915' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='7005' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='7089' u='w' c='gen_function'/>
<use f='tcc/tccgen.c' l='7115' u='w' c='gen_inline_functions'/>
<use f='tcc/tccgen.c' l='7170' u='w' c='decl0'/>
<use f='tcc/tccgen.c' l='7178' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7185' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7197' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7208' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7209' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7242' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7251' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7256' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7257' u='w' c='decl0'/>
<use f='tcc/tccgen.c' l='7257' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7261' u='w' c='decl0'/>
<use f='tcc/tccgen.c' l='7267' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7296' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7299' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7304' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7310' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7321' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7325' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7327' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7330' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7332' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7333' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7334' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7334' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7340' u='w' c='decl0'/>
<use f='tcc/tccgen.c' l='7355' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7363' u='w' c='decl0'/>
<use f='tcc/tccpp.c' l='3071' u='r' c='macro_arg_subst'/>
<use f='tcc/tccpp.c' l='3089' u='r' c='macro_arg_subst'/>
<use f='tcc/tccpp.c' l='3334' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3386' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3404' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3410' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3760' u='r' c='define_print'/>
