<dec f='tcc/tcc.h' l='621' type='uint64_t'/>
<use f='tcc/i386-asm.c' l='418' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='418' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='420' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='420' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='422' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='422' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='425' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='425' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='425' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='425' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='442' u='w' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='450' u='w' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='450' u='r' c='parse_operand'/>
<use f='tcc/i386-asm.c' l='487' u='r' c='gen_expr32'/>
<use f='tcc/i386-asm.c' l='489' u='r' c='gen_expr32'/>
<use f='tcc/i386-asm.c' l='495' u='r' c='gen_expr64'/>
<use f='tcc/i386-asm.c' l='509' u='r' c='gen_disp32'/>
<use f='tcc/i386-asm.c' l='515' u='r' c='gen_disp32'/>
<use f='tcc/i386-asm.c' l='539' u='r' c='asm_modrm'/>
<use f='tcc/i386-asm.c' l='548' u='r' c='asm_modrm'/>
<use f='tcc/i386-asm.c' l='550' u='r' c='asm_modrm'/>
<use f='tcc/i386-asm.c' l='550' u='r' c='asm_modrm'/>
<use f='tcc/i386-asm.c' l='569' u='r' c='asm_modrm'/>
<use f='tcc/i386-asm.c' l='955' u='r' c='asm_opcode'/>
<use f='tcc/i386-asm.c' l='1038' u='r' c='asm_opcode'/>
<use f='tcc/i386-asm.c' l='1042' u='w' c='asm_opcode'/>
<use f='tcc/i386-asm.c' l='1119' u='r' c='asm_opcode'/>
<use f='tcc/i386-asm.c' l='1121' u='r' c='asm_opcode'/>
<offset>0</offset>
<use f='tcc/tccasm.c' l='118' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='122' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='142' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='142' u='r' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='144' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='144' u='r' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='148' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='159' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='172' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='176' u='w' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='205' u='w' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='205' u='r' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='208' u='r' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='212' u='w' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='212' u='r' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='215' u='r' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='217' u='w' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='217' u='r' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='220' u='w' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='220' u='r' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='224' u='w' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='224' u='r' c='asm_expr_prod'/>
<use f='tcc/tccasm.c' l='246' u='w' c='asm_expr_logic'/>
<use f='tcc/tccasm.c' l='246' u='r' c='asm_expr_logic'/>
<use f='tcc/tccasm.c' l='249' u='w' c='asm_expr_logic'/>
<use f='tcc/tccasm.c' l='249' u='r' c='asm_expr_logic'/>
<use f='tcc/tccasm.c' l='253' u='w' c='asm_expr_logic'/>
<use f='tcc/tccasm.c' l='253' u='r' c='asm_expr_logic'/>
<use f='tcc/tccasm.c' l='274' u='w' c='asm_expr_sum'/>
<use f='tcc/tccasm.c' l='274' u='r' c='asm_expr_sum'/>
<use f='tcc/tccasm.c' l='278' u='w' c='asm_expr_sum'/>
<use f='tcc/tccasm.c' l='278' u='r' c='asm_expr_sum'/>
<use f='tcc/tccasm.c' l='293' u='w' c='asm_expr_sum'/>
<use f='tcc/tccasm.c' l='298' u='w' c='asm_expr_sum'/>
<use f='tcc/tccasm.c' l='327' u='w' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='327' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='327' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='330' u='w' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='330' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='330' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='333' u='w' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='333' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='333' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='336' u='w' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='336' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='336' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='339' u='w' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='339' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='339' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='342' u='w' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='342' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='342' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='348' u='w' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='348' u='r' c='asm_expr_cmp'/>
<use f='tcc/tccasm.c' l='363' u='r' c='asm_int_expr'/>
<use f='tcc/tccasm.c' l='416' u='r' c='set_symbol'/>
<use f='tcc/tccasm.c' l='563' u='r' c='asm_parse_directive'/>
<use f='tcc/tccasm.c' l='565' u='r' c='asm_parse_directive'/>
<use f='tcc/tccasm.c' l='648' u='r' c='asm_parse_directive'/>
