<dec f='tcc/tcc.h' l='442' type='CValue'/>
<use f='tcc/i386-asm.c' l='1493' u='m' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1497' u='m' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1500' u='m' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1509' u='m' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1649' u='m' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1677' u='m' c='asm_gen_code'/>
<offset>256</offset>
<doc f='tcc/tcc.h' l='442'>/* constant, if VT_CONST */</doc>
<use f='tcc/tccgen.c' l='659' u='w' c='vsetc'/>
<use f='tcc/tccgen.c' l='690' u='m' c='vpop'/>
<use f='tcc/tccgen.c' l='1003' u='m' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1031' u='m' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1112' u='m' c='move_reg'/>
<use f='tcc/tccgen.c' l='1593' u='m' c='gv_dup'/>
<use f='tcc/tccgen.c' l='1614' u='m' c='gvtst'/>
<use f='tcc/tccgen.c' l='1872' u='m' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1873' u='m' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1935' u='m' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1958' u='m' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1979' u='m' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1994' u='m' c='gen_opic'/>
<use f='tcc/tccgen.c' l='2000' u='m' c='gen_opic'/>
<use f='tcc/tccgen.c' l='2031' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2032' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2034' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2035' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2037' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2038' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2064' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2066' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2068' u='m' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2093' u='m' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2094' u='m' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2096' u='m' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2096' u='m' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2491' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2491' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2493' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2493' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2497' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2498' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2498' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2500' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2500' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2502' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2503' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2503' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2505' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2505' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2509' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2509' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2511' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2511' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2513' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2513' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2515' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2515' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2518' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2518' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2522' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2522' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2528' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2528' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2529' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2534' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2534' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2543' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2545' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2545' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2550' u='m' c='gen_cast'/>
<use f='tcc/tccgen.c' l='3205' u='m' c='vstore'/>
<use f='tcc/tccgen.c' l='3205' u='m' c='vstore'/>
<use f='tcc/tccgen.c' l='4354' u='m' c='post_type'/>
<use f='tcc/tccgen.c' l='4761' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='4761' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='4763' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='4958' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='4960' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='4962' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='5103' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='5105' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='5205' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5205' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5232' u='m' c='unary'/>
<use f='tcc/tccgen.c' l='5253' u='a' c='unary'/>
<use f='tcc/tccgen.c' l='5390' u='m' c='expr_land'/>
<use f='tcc/tccgen.c' l='5431' u='m' c='expr_lor'/>
<use f='tcc/tccgen.c' l='5474' u='m' c='condition_3way'/>
<use f='tcc/tccgen.c' l='5706' u='m' c='expr_const64'/>
<use f='tcc/tccgen.c' l='5766' u='m' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='5796' u='m' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='6539' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6550' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6550' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6552' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6555' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6558' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6561' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6566' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6571' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6576' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6578' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6591' u='m' c='init_putv'/>
<use f='tcc/tccgen.c' l='6606' u='m' c='init_putv'/>
