<dec f='tcc/tcc.h' l='439' type='unsigned short'/>
<use f='tcc/i386-asm.c' l='1262' u='r' c='asm_compute_constraints'/>
<use f='tcc/i386-asm.c' l='1388' u='r' c='asm_compute_constraints'/>
<use f='tcc/i386-asm.c' l='1394' u='r' c='asm_compute_constraints'/>
<use f='tcc/i386-asm.c' l='1408' u='r' c='asm_compute_constraints'/>
<use f='tcc/i386-asm.c' l='1441' u='r' c='asm_compute_constraints'/>
<use f='tcc/i386-asm.c' l='1477' u='r' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1634' u='r' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1640' u='w' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1640' u='r' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1660' u='r' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1664' u='w' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1664' u='r' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1669' u='w' c='asm_gen_code'/>
<use f='tcc/i386-asm.c' l='1669' u='r' c='asm_gen_code'/>
<offset>128</offset>
<doc f='tcc/tcc.h' l='439'>/* register + flags */</doc>
<use f='tcc/tccasm.c' l='1074' u='w' c='subst_asm_operands'/>
<use f='tcc/tccasm.c' l='1075' u='r' c='subst_asm_operands'/>
<use f='tcc/tccasm.c' l='1076' u='w' c='subst_asm_operands'/>
<use f='tcc/tccasm.c' l='1125' u='r' c='parse_asm_operands'/>
<use f='tcc/tccasm.c' l='1126' u='r' c='parse_asm_operands'/>
<use f='tcc/tccasm.c' l='1127' u='r' c='parse_asm_operands'/>
<use f='tcc/tccgen.c' l='127' u='r' c='test_lvalue'/>
<use f='tcc/tccgen.c' l='650' u='r' c='vsetc'/>
<use f='tcc/tccgen.c' l='657' u='w' c='vsetc'/>
<use f='tcc/tccgen.c' l='668' u='r' c='vswap'/>
<use f='tcc/tccgen.c' l='681' u='r' c='vpop'/>
<use f='tcc/tccgen.c' l='958' u='r' c='save_regs'/>
<use f='tcc/tccgen.c' l='984' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='989' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='992' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1002' u='w' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1022' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1026' u='w' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1026' u='r' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1028' u='w' c='save_reg_upstack'/>
<use f='tcc/tccgen.c' l='1073' u='r' c='get_reg'/>
<use f='tcc/tccgen.c' l='1090' u='r' c='get_reg'/>
<use f='tcc/tccgen.c' l='1111' u='w' c='move_reg'/>
<use f='tcc/tccgen.c' l='1120' u='w' c='gaddrof'/>
<use f='tcc/tccgen.c' l='1122' u='r' c='gaddrof'/>
<use f='tcc/tccgen.c' l='1123' u='w' c='gaddrof'/>
<use f='tcc/tccgen.c' l='1123' u='r' c='gaddrof'/>
<use f='tcc/tccgen.c' l='1135' u='w' c='gbound'/>
<use f='tcc/tccgen.c' l='1137' u='r' c='gbound'/>
<use f='tcc/tccgen.c' l='1139' u='r' c='gbound'/>
<use f='tcc/tccgen.c' l='1140' u='r' c='gbound'/>
<use f='tcc/tccgen.c' l='1147' u='w' c='gbound'/>
<use f='tcc/tccgen.c' l='1164' u='w' c='incr_bf_adr'/>
<use f='tcc/tccgen.c' l='1164' u='r' c='incr_bf_adr'/>
<use f='tcc/tccgen.c' l='1172' u='r' c='load_packed_bf'/>
<use f='tcc/tccgen.c' l='1206' u='r' c='store_packed_bf'/>
<use f='tcc/tccgen.c' l='1208' u='r' c='store_packed_bf'/>
<use f='tcc/tccgen.c' l='1245' u='w' c='adjust_bf'/>
<use f='tcc/tccgen.c' l='1245' u='r' c='adjust_bf'/>
<use f='tcc/tccgen.c' l='1294' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1305' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1308' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1312' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1327' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1360' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1369' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1375' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1381' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1387' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1388' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1398' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1405' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1407' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1409' u='r' c='gv'/>
<use f='tcc/tccgen.c' l='1420' u='w' c='gv'/>
<use f='tcc/tccgen.c' l='1438' u='r' c='gv2'/>
<use f='tcc/tccgen.c' l='1445' u='r' c='gv2'/>
<use f='tcc/tccgen.c' l='1456' u='r' c='gv2'/>
<use f='tcc/tccgen.c' l='1592' u='w' c='gv_dup'/>
<use f='tcc/tccgen.c' l='1598' u='w' c='gv_dup'/>
<use f='tcc/tccgen.c' l='1607' u='r' c='gvtst'/>
<use f='tcc/tccgen.c' l='1612' u='r' c='gvtst'/>
<use f='tcc/tccgen.c' l='1870' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1871' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1989' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='1990' u='r' c='gen_opic'/>
<use f='tcc/tccgen.c' l='2027' u='r' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2028' u='r' c='gen_opif'/>
<use f='tcc/tccgen.c' l='2091' u='r' c='is_null_pointer'/>
<use f='tcc/tccgen.c' l='2353' u='r' c='gen_op'/>
<use f='tcc/tccgen.c' l='2378' u='w' c='gen_cvt_itof1'/>
<use f='tcc/tccgen.c' l='2408' u='w' c='gen_cvt_ftoi1'/>
<use f='tcc/tccgen.c' l='2466' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2467' u='w' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2482' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2483' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2549' u='w' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2649' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2652' u='w' c='gen_cast'/>
<use f='tcc/tccgen.c' l='2652' u='r' c='gen_cast'/>
<use f='tcc/tccgen.c' l='3177' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3196' u='r' c='vstore'/>
<use f='tcc/tccgen.c' l='3204' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3207' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3225' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='3236' u='w' c='vstore'/>
<use f='tcc/tccgen.c' l='4353' u='r' c='post_type'/>
<use f='tcc/tccgen.c' l='4495' u='r' c='indir'/>
<use f='tcc/tccgen.c' l='4501' u='w' c='indir'/>
<use f='tcc/tccgen.c' l='4505' u='w' c='indir'/>
<use f='tcc/tccgen.c' l='4759' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4762' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='4855' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5143' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5146' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5147' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5174' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5201' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5216' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5230' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5252' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5252' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5388' u='r' c='expr_land'/>
<use f='tcc/tccgen.c' l='5429' u='r' c='expr_lor'/>
<use f='tcc/tccgen.c' l='5470' u='r' c='condition_3way'/>
<use f='tcc/tccgen.c' l='5471' u='r' c='condition_3way'/>
<use f='tcc/tccgen.c' l='5597' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5597' u='r' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5646' u='w' c='expr_cond'/>
<use f='tcc/tccgen.c' l='5704' u='r' c='expr_const64'/>
<use f='tcc/tccgen.c' l='5765' u='r' c='gfunc_return'/>
<use f='tcc/tccgen.c' l='6289' u='r' c='parse_init_elem'/>
<use f='tcc/tccgen.c' l='6290' u='r' c='parse_init_elem'/>
<use f='tcc/tccgen.c' l='6457' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6462' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6476' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6593' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6608' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6987' u='w' c='decl_initializer_alloc'/>
