<dec f='tcc/tcc.h' l='484' type='int'/>
<offset>0</offset>
<doc f='tcc/tcc.h' l='484'>/* associated number or Elf symbol index */</doc>
<use f='tcc/tccasm.c' l='72' u='w' c='get_asm_sym'/>
<use f='tcc/tccasm.c' l='72' u='r' c='get_asm_sym'/>
<use f='tcc/tccasm.c' l='107' u='r' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='113' u='r' c='asm_expr_unary'/>
<use f='tcc/tccasm.c' l='391' u='r' c='asm_new_label1'/>
<use f='tcc/tccgen.c' l='218' u='r' c='tcc_debug_funcstart'/>
<use f='tcc/tccgen.c' l='286' u='r' c='elfsym'/>
<use f='tcc/tccgen.c' l='288' u='r' c='elfsym'/>
<use f='tcc/tccgen.c' l='350' u='r' c='put_extern_sym2'/>
<use f='tcc/tccgen.c' l='411' u='w' c='put_extern_sym2'/>
<use f='tcc/tccgen.c' l='438' u='r' c='greloca'/>
<use f='tcc/tccgen.c' l='440' u='r' c='greloca'/>
<use f='tcc/tccgen.c' l='509' u='w' c='sym_push2'/>
<use f='tcc/tccgen.c' l='882' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='884' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='885' u='w' c='patch_type'/>
<use f='tcc/tccgen.c' l='885' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='886' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='886' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='2669' u='r' c='type_size'/>
<use f='tcc/tccgen.c' l='2677' u='r' c='type_size'/>
<use f='tcc/tccgen.c' l='2680' u='r' c='type_size'/>
<use f='tcc/tccgen.c' l='2685' u='r' c='type_size'/>
<use f='tcc/tccgen.c' l='2729' u='r' c='vla_runtime_type_size'/>
<use f='tcc/tccgen.c' l='2951' u='r' c='type_to_str'/>
<use f='tcc/tccgen.c' l='3485' u='w' c='struct_add_offset'/>
<use f='tcc/tccgen.c' l='3659' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3662' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3668' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3670' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3692' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3712' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3718' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3739' u='w' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3803' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3852' u='w' c='struct_decl'/>
<use f='tcc/tccgen.c' l='3992' u='r' c='parse_btype_qualify'/>
<use f='tcc/tccgen.c' l='4662' u='w' c='unary'/>
<use f='tcc/tccgen.c' l='5096' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='5136' u='r' c='unary'/>
<use f='tcc/tccgen.c' l='6353' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6353' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6357' u='w' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6375' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6387' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6388' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6388' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6399' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6667' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6737' u='w' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6746' u='w' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6773' u='w' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6783' u='r' c='decl_initializer'/>
<use f='tcc/tccgen.c' l='6841' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='6887' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='6888' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='6947' u='r' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='7039' u='w' c='decl_initializer_alloc'/>
<use f='tcc/tccgen.c' l='7109' u='r' c='gen_inline_functions'/>
<use f='tcc/tccgen.c' l='7197' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7198' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7335' u='r' c='decl0'/>
<use f='tcc/tccpp.c' l='1395' u='r' c='label_pop'/>
