<dec f='tcc/tcc.h' l='479' type='int'/>
<use f='tcc/i386-asm.c' l='1483' u='r' c='subst_asm_operand'/>
<use f='tcc/i386-asm.c' l='1484' u='r' c='subst_asm_operand'/>
<offset>0</offset>
<doc f='tcc/tcc.h' l='479'>/* symbol token */</doc>
<use f='tcc/tccasm.c' l='815' u='r' c='asm_parse_directive'/>
<use f='tcc/tccgen.c' l='351' u='r' c='put_extern_sym2'/>
<use f='tcc/tccgen.c' l='357' u='r' c='put_extern_sym2'/>
<use f='tcc/tccgen.c' l='507' u='w' c='sym_push2'/>
<use f='tcc/tccgen.c' l='521' u='r' c='sym_find2'/>
<use f='tcc/tccgen.c' l='523' u='r' c='sym_find2'/>
<use f='tcc/tccgen.c' l='609' u='r' c='sym_pop'/>
<use f='tcc/tccgen.c' l='852' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='864' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='871' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='887' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='891' u='r' c='patch_type'/>
<use f='tcc/tccgen.c' l='2928' u='r' c='type_to_str'/>
<use f='tcc/tccgen.c' l='3464' u='r' c='find_field'/>
<use f='tcc/tccgen.c' l='3466' u='r' c='find_field'/>
<use f='tcc/tccgen.c' l='3471' u='r' c='find_field'/>
<use f='tcc/tccgen.c' l='3480' u='r' c='struct_add_offset'/>
<use f='tcc/tccgen.c' l='3482' u='r' c='struct_add_offset'/>
<use f='tcc/tccgen.c' l='3589' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3638' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3647' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3662' u='r' c='struct_layout'/>
<use f='tcc/tccgen.c' l='3888' u='r' c='struct_decl'/>
<use f='tcc/tccgen.c' l='6202' u='r' c='block'/>
<use f='tcc/tccgen.c' l='6291' u='r' c='parse_init_elem'/>
<use f='tcc/tccgen.c' l='6394' u='r' c='decl_designator'/>
<use f='tcc/tccgen.c' l='6462' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='6477' u='r' c='init_putv'/>
<use f='tcc/tccgen.c' l='7060' u='r' c='gen_function'/>
<use f='tcc/tccgen.c' l='7179' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7249' u='r' c='decl0'/>
<use f='tcc/tccgen.c' l='7291' u='r' c='decl0'/>
<use f='tcc/tccpp.c' l='1319' u='r' c='define_undef'/>
<use f='tcc/tccpp.c' l='1346' u='r' c='free_defines'/>
<use f='tcc/tccpp.c' l='1390' u='r' c='label_pop'/>
<use f='tcc/tccpp.c' l='1393' u='r' c='label_pop'/>
<use f='tcc/tccpp.c' l='1402' u='r' c='label_pop'/>
<use f='tcc/tccpp.c' l='1624' u='r' c='pragma_parse'/>
<use f='tcc/tccpp.c' l='3089' u='r' c='macro_arg_subst'/>
<use f='tcc/tccpp.c' l='3237' u='r' c='next_argstream'/>
<use f='tcc/tccpp.c' l='3240' u='w' c='next_argstream'/>
<use f='tcc/tccpp.c' l='3380' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3404' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3419' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3440' u='r' c='macro_subst_tok'/>
<use f='tcc/tccpp.c' l='3765' u='r' c='define_print'/>
